export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const CANCEL_LOGIN = 'CANCEL_LOGIN'
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
export const LOGIN_ADMIN_PASS = 'LOGIN_ADMIN_PASS'
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL'
export const SELECT_LOGOUT = 'SELECT_LOGOUT'
export const SELECT_DASHBOARD = 'SELECT_DASHBOARD'
export const LOGOUT_ADMIN_PASS = 'LOGOUT_ADMIN_PASS'
export const GOTO_ADMIN_DASHBOARD = 'GOTO_ADMIN_DASHBOARD'
export const REDIRECT_DASHBOARD = 'REDIRECT_DASHBOARD'
export const REDIRECT_HOME = 'REDIRECT_HOME'

// Fetching Student Data
export const GET_STUDENTS = 'GET_STUDENTS'
export const GET_STUDENTS_PASS = 'GET_STUDENTS_PASS'
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL'
export const GET_STUDENT_SINGLE = 'GET_STUDENT_SINGLE'
export const GET_STUDENT_SINGLE_PASS = 'GET_STUDENT_SINGLE_PASS'
export const GET_STUDENT_SINGLE_FAIL = 'GET_STUDENT_SINGLE_FAIL'


// Jwt Token Key
export const ACCESS_TOKEN = 'accessToken'