// Primely Home Actions
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const CANCEL_LOGIN = 'CANCEL_LOGIN'
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
export const LOGIN_ADMIN_PASS = 'LOGIN_ADMIN_PASS'
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL'
export const SELECT_LOGOUT = 'SELECT_LOGOUT'
export const SELECT_DASHBOARD = 'SELECT_DASHBOARD'
export const LOGOUT_ADMIN_PASS = 'LOGOUT_ADMIN_PASS'
export const GOTO_ADMIN_DASHBOARD = 'GOTO_ADMIN_DASHBOARD'
export const REDIRECT_DASHBOARD = 'REDIRECT_DASHBOARD'
export const REDIRECT_HOME = 'REDIRECT_HOME'

// Fetching Student Data
export const GET_STUDENTS = 'GET_STUDENTS'
export const GET_STUDENTS_PASS = 'GET_STUDENTS_PASS'
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL'
export const GET_STUDENT_SINGLE = 'GET_STUDENT_SINGLE'
export const GET_STUDENT_SINGLE_PASS = 'GET_STUDENT_SINGLE_PASS'
export const GET_STUDENT_SINGLE_FAIL = 'GET_STUDENT_SINGLE_FAIL'

//export const CREATE_STUDENT = 'CREATE_STUDENT'
export const CREATE_SUBMIT_STUDENT_FAIL = 'CREATE_SUBMIT_STUDENT_FAIL'
export const CANCEL_STUDENT = 'CANCEL_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL'
export const DELETE_STUDENT_CACHE = 'DELETE_STUDENT_CACHE'
export const SUBMIT_STUDENT = 'SUBMIT_STUDENT'
//export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_SUBMIT_STUDENT_FAIL = 'UPDATE_SUBMIT_STUDENT_FAIL'
export const DELETE_STUDENT_MODAL = 'DELETE_STUDENT_MODAL'
export const TOGGLE_DELETE_MODAL = 'TOGGLE_DELETE_MODAL'
export const CANCEL_DELETE_MODAL = 'CANCEL_DELETE_MODAL'

//Route changer -  from UI
export const ADD_STUDENT = 'ADD_STUDENT'
export const SELECT_STUDENT = 'SELECT_STUDENT'
export const EDIT_STUDENT = 'EDIT_STUDENT'
export const BACK_HOME = 'HOME_BACK'

//Route changer - from Saga
export const DELETE_STUDENT_PASS = 'DELETE_STUDENT_PASS'
export const CREATE_SUBMIT_STUDENT_PASS = 'CREATE_SUBMIT_STUDENT_PASS'
export const UPDATE_SUBMIT_STUDENT_PASS = 'UPDATE_SUBMIT_STUDENT_PASS'
//export const CANCEL_CREATE_STUDENT = 'CANCEL_CREATE_STUDENT'
//export const CANCEL_UPDATE_STUDENT = 'CANCEL_UPDATE_STUDENT'


// Jwt Token Key
export const ACCESS_TOKEN = 'accessToken'